//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using CapaEntidad;
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Bateria> Baterias { get; set; }
        public virtual DbSet<datos_Accesories> datos_Accesories { get; set; }
        public virtual DbSet<datos_Cargadores> datos_Cargadores { get; set; }
        public virtual DbSet<datos_Ram> datos_Ram { get; set; }
        public virtual DbSet<Desktop> Desktops { get; set; }
        public virtual DbSet<DiscosDuro> DiscosDuros { get; set; }
        public virtual DbSet<laptop> laptops { get; set; }
        public virtual DbSet<Monitore> Monitores { get; set; }
    }
}
