//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class datos_Ram
    {
        public int id { get; set; }
        public string Descripcion { get; set; }
        public string Capacity { get; set; }
        public string FormFactor { get; set; }
        public string Frequency { get; set; }
        public string Slot { get; set; }
        public int Quantity { get; set; }
        public string Price { get; set; }
        public string Observacion { get; set; }
        public string ReservadoPor { get; set; }
    }
}
